-- Migration number: 0001 generated by teenybase on 2025-03-18T17:25:28.930Z. Do not modify this file.

CREATE TABLE urls (
	name TEXT NOT NULL, 
	link TEXT NOT NULL, 
	slug TEXT UNIQUE NOT NULL, 
	views INTEGER DEFAULT 0, 
	created_by TEXT NOT NULL REFERENCES users(id), 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_urls_created_by ON urls (created_by);
CREATE UNIQUE INDEX idx_urls_slug ON urls (slug COLLATE NOCASE);
CREATE TRIGGER tgr_urls_raise_on_created_update BEFORE UPDATE OF created ON urls BEGIN SELECT RAISE(FAIL, 'Cannot update created column') WHERE OLD.created != NEW.created; END;